# Environment settings
gpus_id: '0'
workers: 1
isdebug: False
is_fine_tune: True
label_radio: 0.1

# Hyperparameters
seed: 42
run_total: 1
batch_size: 4
epochs: 10
backbone: "resnet50"
pretrained: True
pretrained_path: "../MasterPaper_new/logs/Exam001_Test1101_CoNSeP_noAspp_modistain_finetune_10_91split_0/checkpoint_10.tar"
projection_dim: 64
model_type: "noAspp"
freeze: True
sparse_radio: 0.6

# Loss options
optimizer: "Adam"
learning_rate: 5.0e-4
weight_decay: 1.0e-6
temperature: 0.5
lr_scheduler: "(x, 25)"
                    
# Dataset Information
dataset_name: "CoNSeP"
data_path: "../Datasets/"
preprocessing_mode: "modistain"

# Image information
act_shape: [256, 256]
out_shape: [256, 256]
nr_types: 5
type_classification: True

# Save Information
Today_date: "Test_date"
other_info: "_epoch10"
save_log_path: "./logs/"
save_per_step: 50
experiment_id: "001_Test_date_"